### ISSUE TITLE
A few questions about input arguments of `getDAcells` and `STGmarkerFinder`

### ISSUE THREAD

**Issue by altairwei** [KlugerLab/DAseq#7]
{DAseq} is a wonderful tool! I'm surprised by it's ability to detect DA cell subpopulation between two different conditions. The tutorial is written in a clear and straightforward manner, however there are two points that are not explained and emphasized in the tutorial.

**1. What's the exact data type of `X` in `getDAcells` arguments?**

In the paper (Zhao, J. et al., *Proceedings of the National Academy of Sciences*, 2021), `X` was described as a dimensional profile of cells.

> Let `X = {x1, . . . , xn} ∈ Rm×n` , where `n` is the number of cells, and `xi` is the m-dimensional profile of cell `i`.

So, in an **integrated** dataset created by {Seurat} following this [tutorial](https://satijalab.org/seurat/articles/integration_introduction.html), `X` could be prepared with the `Seurat::Embeddings(obj[["pca"]])[, 1:10]` command, right?

**2. What kind of expression matrix does `STGmarkerFinder` require?**

In {DAseq} tutorial, I have noticed that `X.data.melanoma` was read from a file named with `_TPM` suffix.

> GSE120575_Sade_Feldman_melanoma_single_cells_TPM_GEO.txt.gz

But in the help page of `STGmarkerFinder`, the argument `X` is documented as following:

> X - matrix, normalized expression matrix of all cells in the dataset, genes are in rows, rownames must be gene names

What kind of expression matrix should be provided? TPM matrix, {Seurat} LogNormalized expression matrix or raw count matrix?

**Comment by altairwei** [comment]
I have found all answers from https://github.com/KlugerLab/DAseq-paper, thank you!

**Comment by LeoCao-X** [comment]
> I have found all answers from https://github.com/KlugerLab/DAseq-paper, thank you!

Sorry to bother you. Have you figured out which kind of matrix to use for STGmarkerFinder() function? I have read the paper but I did not find the related answer.

**Comment by altairwei** [comment]
> Sorry to bother you. Have you figured out which kind of matrix to use for STGmarkerFinder() function? I have read the paper but I did not find the related answer.

LogNormalized expression is ok, see https://github.com/KlugerLab/DAseq-paper/blob/6f9195e13292fce853b16c50cc6b42bc91e43d74/DAseq_mouseSkin.R#L265

**Comment by LeoCao-X** [comment]
> > Sorry to bother you. Have you figured out which kind of matrix to use for STGmarkerFinder() function? I have read the paper but I did not find the related answer.
> 
> LogNormalized expression is ok, see https://github.com/KlugerLab/DAseq-paper/blob/6f9195e13292fce853b16c50cc6b42bc91e43d74/DAseq_mouseSkin.R#L265

Thanks very much!
